CREATE TABLE IF NOT EXISTS `Kmarket`.`km_cs_notice`(
	`notNo` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	`uid` VARCHAR(20) NOT NULL,
	`csType` VARCHAR(30) NOT NULL,
	`c1Name` VARCHAR(20) NOT NULL,
	`notTitle` VARCHAR(50) NOT NULL,
	`notContent` VARCHAR(255) NOT NULL,
	`hit` INT NULL,
	`regip` VARCHAR(100) NOT NULL,
	`rdate` DATETIME NOT NULL
	  )
ENGINE = INNODB;